[versions]
kotlin = "1.9.23"

[libraries]
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version = "1.9.23-1.0.19" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }