[versions]
kotlin = "1.9.0"

[libraries]
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version = "1.9.0-1.0.11" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }